### ISSUE TITLE
Fade

### ISSUE THREAD

**Issue by ghost** [Real-Wizard/Wizard-Cogs#2]
Hey man, love the rainbow cog, but i would love to be able to put the change speed up really fast and have it loop through all the hexadecimal values, any idea how i could do this? I can easily change the speed but I have no idea how to get it to loop through colour values.

Thanks! Will.

**Comment by Real-Wizard** [comment]
Well iam happy you like my code and so lets start
first to make it faster you could use the arainbow command but it has to be higher than 120 due to discord tos ect
second my code uses a random color gen as u can see in 
`
            colour = ''.join([choice('0123456789ABCDEF') for x in range(6)])
 `
So it goes through all color values i hope i have helped you
-Neo

**Comment by ghost** [comment]
Hey, thanks for the reply, do you know how you could get it to fade from black to white, to black, going through all hexadecimal values on the way? So instead of choosing random values every 120secs, you could increment 1 from the previous colour?

Will

Sent from Mail for Windows 10

**Comment by Real-Wizard** [comment]
Dont Realy Understand What You Mean

**Comment by ghost** [comment]
Hey,

So if you were to build on top of your existing code, so instead of
choosing random colours it faded, like the background of this
<https://www.kahoot.it> website. Could you help me in doing this? As I'm
not sure how you would increment the hexadecimal value as to get it to go
in an infinite loop, creating a fade effect on the name of the user.

Thanks,

WIll

**Comment by Real-Wizard** [comment]
not sure but that would add some lines, i will talk this in concedration after i finish [this](https://github.com/Real-Wizard/Wizard-Cogs/projects/1)
