### ISSUE TITLE
Command for rainbow cog

### ISSUE THREAD

**Issue by g3bdou** [Real-Wizard/Wizard-Cogs#4]
Could you add a command that stop rainbow color please?

**Comment by Electromaster232** [comment]
Don't use the cog all together it's API abuse and you could get IP banned from Discord

It's a shame too it's a cool cog.

**Comment by yamariha** [comment]
i cant get the cog working i get discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions

**Comment by yamariha** [comment]
Error in command 'rainbow'. Check your console or logs for details.
